name: Update data

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2

      - name: Get users data
        run: |
          deno run --allow-net --allow-write getUsers.js

      - name: Write record.js
        run: |
          deno run --allow-read --allow-write record.js

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.5.1
        with:
          commit_message: ${{ steps.date.outputs.date }} Daily data refreshing
